resolver: lts-18.16

packages: 
  - '.'

extra-deps:
  - text-format-heavy-0.1.5.3
  - haskell-gettext-0.1.2.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

